plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

version = mod_version
group = mod_group_id
base { archivesName = "No-Sugar" }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

configurations {
    shadowImpl
    agentImpl
    embeddedAgentCompileOnly
    embeddedAgentImplementation.extendsFrom agentImpl
    compileOnly.extendsFrom shadowImpl
}

sourceSets {
    embeddedAgent {
        java {
            srcDirs = ['src/main/java']
            include 'com/test/nosugar/agent/**'
        }
        resources {
            srcDirs = ['src/main/resources']
            include 'com/test/nosugar/agent/**'
            exclude 'assets/**', 'data/**', 'META-INF/mods.toml', 'pack.mcmeta', 'nosugar.mixins.json'
        }
        compileClasspath += configurations.minecraft
        compileClasspath += configurations.agentImpl
    }
    main {
        java {
            srcDirs = ['src/main/java']
            include 'com/test/nosugar/**'
            exclude 'com/test/nosugar/agent/**'
        }
        resources {
            srcDirs = ['src/main/resources', 'src/generated/resources']
            exclude 'com/test/nosugar/agent/**'
        }
        compileClasspath += sourceSets.embeddedAgent.output
        runtimeClasspath += sourceSets.embeddedAgent.output
    }
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    copyIdeResources = true
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                    source sourceSets.embeddedAgent
                }
            }
        }
        client { property 'forge.enabledGameTestNamespaces', mod_id }
        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }
        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            property 'mixin.config.disable', 'true'
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://maven.kosmx.dev/" }
    maven { url "https://maven.theillusivec4.top/" }
    maven { url "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/" }
    maven { url 'https://jitpack.io' }
    maven { url "https://www.cursemaven.com" }
    flatDir { dirs 'libs' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    implementation jarJar("io.github.llamalad7:mixinextras-forge:0.5.3") { jarJar.ranged(it, "[0.5.3,)") }
    compileOnly("io.github.llamalad7:mixinextras-common:0.5.3")
    implementation fg.deobf("curse.maven:geckolib-388172:7553267")
    implementation fg.deobf("curse.maven:playeranimator-658587:4587214")
    implementation fg.deobf("curse.maven:curios-309927:6418456")
    implementation fg.deobf("curse.maven:slashblade-resharped-1022428:7363505")
    implementation fg.deobf("curse.maven:irons-spells-n-spellbooks-855414:7691158")
    implementation fg.deobf("curse.maven:tinkers-construct-74072:7449219")
    implementation fg.deobf("curse.maven:mantle-74924:7563777")
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.5.3"

    agentImpl "org.ow2.asm:asm:9.9.1"
    agentImpl "org.ow2.asm:asm-tree:9.9.1"
    agentImpl "org.ow2.asm:asm-commons:9.9.1"

}

def replaceProperties = [
        minecraft_version      : minecraft_version, minecraft_version_range: minecraft_version_range,
        forge_version          : forge_version,         forge_version_range    : forge_version_range,
        loader_version_range   : loader_version_range,  mod_id                 : mod_id,
        mod_name               : mod_name,              mod_license            : mod_license,
        mod_version            : mod_version,           mod_authors            : mod_authors,
        mod_description        : mod_description
]

tasks.named('processResources', ProcessResources).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.properties replaceProperties
    from sourceSets.main.resources.srcDirs
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('processEmbeddedAgentResources', ProcessResources).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.register('embeddedAgentJar', ShadowJar) {
    dependsOn 'compileEmbeddedAgentJava', 'processEmbeddedAgentResources'
    from sourceSets.embeddedAgent.output
    configurations = [project.configurations.agentImpl]

    relocate 'org.objectweb.asm', 'com.test.nosugar.shadow.asm'

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    destinationDirectory = layout.buildDirectory.dir('embedded')
    archiveBaseName = 'nosugar-agent'
    archiveVersion = ""
    archiveClassifier = ''
    archiveExtension = 'jar'

    manifest {
        attributes(
                'Manifest-Version': '1.0',
                'Agent-Class': 'com.test.nosugar.agent.NSAgent',
                'Can-Retransform-Classes': 'true',
                'Can-Redefine-Classes': 'true',
                'Premain-Class': 'com.test.nosugar.agent.NSAgent',
                'Boot-Class-Path': 'nosugar-agent.jar'
        )
    }
}

tasks.register('reobfEmbeddedJar', JavaExec) {
    dependsOn 'embeddedAgentJar', 'createMcpToSrg'
    def inputJar = layout.buildDirectory.file('embedded/nosugar-agent.jar')
    def outputJar = layout.buildDirectory.file('embedded/nosugar-agent.jar.embed')
    def mappingsFile = tasks.named('createMcpToSrg').flatMap { it.output }

    inputs.file(inputJar)
    inputs.file(mappingsFile)
    outputs.file(outputJar)

    classpath = configurations.detachedConfiguration(
            dependencies.create('net.minecraftforge:renamer:2.0.4:all')
    )
    mainClass = 'net.minecraftforge.renamer.Main'

    doFirst {
        def argsList = [
                '--input', inputJar.get().asFile.absolutePath,
                '--output', outputJar.get().asFile.absolutePath,
                '--names', mappingsFile.get().asFile.absolutePath,
                '--disable-abstract-param'
        ]
        sourceSets.embeddedAgent.compileClasspath.files.each {
            if (it.exists()) argsList.addAll(['--lib', it.absolutePath])
        }
        args = argsList
    }
}

shadowJar {
    dependsOn('reobfEmbeddedJar')
    configurations = [project.configurations.shadowImpl]
    from sourceSets.main.output

    exclude 'META-INF/maven/**', 'META-INF/NOTICE', 'META-INF/versions/**', 'module-info.class'


    archiveClassifier = 'all'
}

tasks.named('jar', Jar) {
    archiveClassifier = 'raw'
    from sourceSets.main.output
    from sourceSets.embeddedAgent.output
}

tasks.named('jarJar') {
    dependsOn('shadowJar')
    archiveClassifier = ''

    into('META-INF/jarjar') {
        from(tasks.named('reobfEmbeddedJar')) {
            rename { it.replace('.embed', '') }
        }
    }

    enabled = true
    doFirst { mainSpec.sourcePaths.clear() }
    from(provider {
        zipTree(shadowJar.archiveFile.get().asFile)
    }) {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
}

afterEvaluate {
    tasks.named('reobfJar') {
        input = tasks.named('jarJar').flatMap { it.archiveFile }
    }
}

mixin {
    config 'nosugar.mixins.json'
    add sourceSets.main, "nosugar.refmap.json"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}