modLoader = "javafml"
loaderVersion = "[47,)" # 1.20.1
license = "MIT"

[[mods]]
modId = "nosugar_core"
version = "${mod_version}"
displayName = "NoSugar Core"
authors = "test"
description = '''
:3
'''

[[dependencies.nosugar_core]]
modId = "forge"
mandatory = true
versionRange = "[47,)" # 1.20.x?
ordering = "NONE"
side = "BOTH"

[[dependencies.nosugar_core]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
